# Generated by Django 4.1.7 on 2023-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.CharField(max_length=1024)),
                ('external_resources', models.CharField(max_length=1024)),
            ],
        ),
    ]
