# Generated by Django 4.1.7 on 2023-03-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, unique=True)),
                ('answer', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('external_resources', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
